steps:
  # Build the Docker image with SHA tag and latest tag
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_GCR_REGION}/${_PROJECT_ID}/${_IMAGE_NAME}:$COMMIT_SHA'
      - '-t'
      - '${_GCR_REGION}/${_PROJECT_ID}/${_IMAGE_NAME}:latest'
      - '.'
    id: 'build-image'

  # Push image with SHA tag
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_GCR_REGION}/${_PROJECT_ID}/${_IMAGE_NAME}:$COMMIT_SHA'
    id: 'push-image-sha'

  # Push latest tag
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_GCR_REGION}/${_PROJECT_ID}/${_IMAGE_NAME}:latest'
    id: 'push-image-latest'

# Images to store in GCR
images:
  - '${_GCR_REGION}/${_PROJECT_ID}/${_IMAGE_NAME}:$COMMIT_SHA'
  - '${_GCR_REGION}/${_PROJECT_ID}/${_IMAGE_NAME}:latest'

# Build options
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

# Timeout for the build
timeout: '1200s'

# Tags for the build
tags:
  - 'docker'
  - '${_IMAGE_NAME}'
