steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'europe-west6-docker.pkg.dev/heart-beats-x/beats-backend/backend', '.' ]
images:
- 'europe-west6-docker.pkg.dev/heart-beats-x/beats-backend/backend'
