version: "3.3"

services:
  api:
    image: ptc:latest
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - src/.env
    ports:
      - "7999:7999"
    volumes:
      - ./src:/src
