version: "3.3"

services:
  api:
    image: ptc:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PORT: 80
    env_file:
      - src/.env
    ports:
      - "7999:80"
    volumes:
      - ./src:/src
