// API client and error handling
export {
	ApiError,
	type ApiErrorField,
	apiClient,
	apiFieldErrors,
	apiMutate,
	del,
	describeError,
	get,
	type MutateOptions,
	type MutateResult,
	post,
	put,
	replayMutation,
} from "./client";
// Generated OpenAPI types (see ./schema.ts for ergonomic re-exports)
export type { Paths, Schemas } from "./schema";
// Re-export types
export type {
	ApiAbsence,
	ApiBeat,
	ApiContract,
	ApiContractTerm,
	ApiGoalOverride,
	ApiProject,
	ApiProjectKind,
	ApiProjectListItem,
	CalendarStatus,
	FlowTopBucket,
	FlowWindow,
	FlowWindowSummary,
	FocusScore,
	Gap,
	GitCommitDay,
	GitHubStatus,
	HeatmapDay,
	InsightCard,
	PatternsResponse,
	ProductivityScore,
	ProjectBreakdownEntry,
	ProjectHealth,
	ProjectTotal,
	RhythmSlot,
	ScoreHistoryItem,
	TimerStatus,
	WeekBreakdown,
	WeeklyDigest,
} from "./schemas";
// Zod schemas for validation
export {
	AbsenceTypeSchema,
	ApiAbsenceListSchema,
	ApiAbsenceSchema,
	ApiBeatListSchema,
	ApiBeatSchema,
	ApiProjectListItemSchema,
	ApiProjectListSchema,
	ApiProjectSchema,
	CalendarStatusSchema,
	ContractSchema,
	ContractTermSchema,
	FlowTopBucketSchema,
	FlowWindowListSchema,
	FlowWindowSchema,
	FlowWindowSummarySchema,
	FocusScoreListSchema,
	GapListSchema,
	GitCommitActivitySchema,
	GitHubStatusSchema,
	HeatmapDayListSchema,
	HolidayListSchema,
	HolidaySchema,
	PatternsResponseSchema,
	ProductivityScoreSchema,
	ProjectBreakdownEntrySchema,
	ProjectHealthListSchema,
	ProjectKindSchema,
	ProjectTotalSchema,
	parseApiResponse,
	RegionListSchema,
	RegionSchema,
	RhythmSlotListSchema,
	ScheduleTypeSchema,
	ScoreHistorySchema,
	TimerStatusSchema,
	WeekBreakdownSchema,
	WeeklyDigestListSchema,
	WeeklyDigestSchema,
} from "./schemas";
