/**
 * Shared API layer - public API
 */

// API client and error handling
export {
	ApiError,
	apiClient,
	apiMutate,
	del,
	get,
	type MutateOptions,
	type MutateResult,
	patch,
	post,
	put,
	replayMutation,
} from "./client";
// Generated OpenAPI types (see ./schema.ts for ergonomic re-exports)
export type { Paths, Schemas } from "./schema";
// Re-export types
export type {
	ApiBeat,
	ApiGoalOverride,
	ApiProject,
	CalendarEvent,
	CalendarStatus,
	DailyNote,
	EstimationAccuracy,
	FlowWindow,
	FocusScore,
	Gap,
	GitHubStatus,
	HeatmapDay,
	InsightCard,
	Intention,
	MoodCorrelation,
	PatternsResponse,
	ProductivityScore,
	ProjectHealth,
	ProjectTotal,
	RhythmSlot,
	ScoreHistoryItem,
	Suggestion,
	TimerStatus,
	WeekBreakdown,
	WeeklyDigest,
} from "./schemas";
// Zod schemas for validation
export {
	ApiBeatListSchema,
	ApiBeatSchema,
	ApiProjectListSchema,
	ApiProjectSchema,
	CalendarEventListSchema,
	CalendarStatusSchema,
	DailyNoteSchema,
	EstimationAccuracyListSchema,
	FlowWindowListSchema,
	FlowWindowSchema,
	FocusScoreListSchema,
	GapListSchema,
	GitHubStatusSchema,
	HeatmapDayListSchema,
	IntentionListSchema,
	IntentionSchema,
	MoodCorrelationSchema,
	PatternsResponseSchema,
	ProductivityScoreSchema,
	ProjectHealthListSchema,
	ProjectTotalSchema,
	parseApiResponse,
	RhythmSlotListSchema,
	ScoreHistorySchema,
	SuggestionListSchema,
	safeParseApiResponse,
	TimerStatusSchema,
	WeekBreakdownSchema,
	WeeklyDigestListSchema,
	WeeklyDigestSchema,
} from "./schemas";
