version: "3.3"

services:
  api:
    image: ptc:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: timekeeper
      MONGO_INITDB_ROOT_PASSWORD: forestclock

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: timekeeper
      ME_CONFIG_MONGODB_ADMINPASSWORD: forestclock
