version: "3.3"

services:
  api:
    image: ptc:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
