/**
 * Project Entity - public API
 *
 * This entity represents a project in the time tracking system.
 * Following FSD conventions, this module exports:
 * - Model: types, domain logic, mappers
 * - API: data fetching hooks and functions
 * - UI: presentational components
 */

// API layer
export {
	archiveProject,
	createProject,
	fetchContractWeek,
	fetchHolidayRegions,
	fetchProjectHolidays,
	fetchProjects,
	fetchProjectTotal,
	fetchProjectWeek,
	holidayRegionKeys,
	projectKeys,
	unarchiveProject,
	updateContract,
	useArchivedProjects,
	useArchiveProject,
	useContractWeek,
	useCreateProject,
	useHolidayRegions,
	useProject,
	useProjectHolidays,
	useProjects,
	useProjectWeeks,
	useUnarchiveProject,
	useUpdateContract,
	useUpdateGoalOverrides,
	useUpdateProject,
} from "./api";
// Model layer
export type {
	Contract,
	ContractDay,
	ContractDayAbsence,
	ContractFieldErrors,
	ContractFrameErrors,
	ContractFrameValues,
	ContractTerm,
	ContractWeek,
	DailySummary,
	GoalOverride,
	Holiday,
	HolidayRegion,
	Project,
	ProjectKind,
	ProjectWithDuration,
	ScheduleType,
	TermFieldErrors,
	TermFormValues,
	WeekGoalView,
	WeekHours,
} from "./model";
export {
	assignColor,
	type BalanceTone,
	balanceTone,
	clearPickerRecents,
	clearPins,
	contractFieldErrors,
	contractFrameDefaults,
	contractFromForm,
	contractGovernsWeek,
	describeBalance,
	describeTerm,
	displayTermOn,
	extractCategories,
	type FilterAndRankOptions,
	filterAndRankProjects,
	formatSignedHours,
	fromPercent,
	isPinned,
	isTimeBased,
	isTimeBasedOn,
	isVisibleProject,
	partitionByArchived,
	readPickerRecents,
	readPins,
	recordPickerRecent,
	SCHEDULE_TYPE_LABELS,
	type SearchField,
	sortProjectsForList,
	sortTerms,
	termFormDefaults,
	termFromForm,
	termHoursPerDay,
	termHoursPerWeek,
	termOn,
	toApiContract,
	toContract,
	toContractWeek,
	togglePin,
	toPercent,
	toProject,
	usePinnedProjects,
	validateContractFrame,
	validateTerm,
	visibleProjects,
	weekGoalView,
} from "./model";

// UI layer
export {
	AdvancedFields,
	type AdvancedFieldsProps,
	type AdvancedFieldsValues,
	BalanceChip,
	ContractTermFields,
	type ContractTermFieldsProps,
	isInlineFormError,
	isValidGithubRepo,
	LoadingSpinner,
	NewProjectDialog,
	ProjectForm,
	type ProjectFormAutoFocusField,
	type ProjectFormErrors,
	type ProjectFormProps,
	type ProjectFormValues,
	ProjectPicker,
	type ProjectPickerProps,
	projectFormFieldErrors,
	projectWriteFromForm,
} from "./ui";
