steps:
  # Install dependencies (pnpm will be installed in the same step)
  - name: 'node:25'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        npm install -g pnpm@10.14.0
        pnpm install --frozen-lockfile
    id: 'install-deps'

  # Build the client
  - name: 'node:25'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        npm install -g pnpm@10.14.0
        pnpm run build
    id: 'build-client'

  # Upload files to Cloud Storage bucket
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gsutil'
    args:
      - '-m'
      - 'rsync'
      - '-r'
      - '-d'
      - 'dist/spa'
      - 'gs://${_UI_BUCKET_NAME}'
    id: 'deploy-to-storage'

# Build options
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

# Timeout for the build
timeout: '1200s'

# Tags for the build
tags:
  - 'ui'
  - 'static-site'
